services:
  - type: web
    name: image-recommendation-system
    env: docker
    plan: starter
    region: oregon
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true 